"""
Session Handoff标准化 — 消除session间信息丢失
==============================================
每次session结束前调用，强制4项必填：做了什么、怎么做的、为什么、下一步精确输入。

用法:
  python3 session_handoff.py write \\
    --what "GPU部署完成, LightGBM CUDA编译" \\
    --how "cmake -DCMAKE_CUDA_ARCHITECTURES='75;80;86;89', make -j, pip install" \\
    --why "compute_60不支持CUDA 13.3, 只编译75+" \\
    --next "评分脚本跑一次验证device=cuda生效" \\
    --files "models/us/arrow_v12_lambdamart.txt,scripts/us/arrow_v12_lambdamart_score.py"

  # 读取上一个session的handoff
  python3 session_handoff.py read

  # 列出所有handoff历史
  python3 session_handoff.py list
"""
import json, sys, os
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).resolve().parent.parent.parent.parent
HANDOFF_DIR = ROOT / "data" / "handoffs"
HANDOFF_CURRENT = ROOT / "session-handoff.md"


def write_handoff(what: str, how: str, why: str, next_step: str,
                  files: str = "", session_id: str = "", risks: str = ""):
    """写标准化handoff"""
    HANDOFF_DIR.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    sid = session_id or os.environ.get("HERMES_SESSION_ID", date_str)

    entry = {
        "timestamp": timestamp,
        "session_id": sid,
        "what": what,
        "how": how,
        "why": why,
        "next_step": next_step,
        "files_changed": [f.strip() for f in files.split(",") if f.strip()],
        "risks": risks,
    }

    # 写历史记录
    history_file = HANDOFF_DIR / f"{date_str}.json"
    with open(history_file, "w") as f:
        json.dump(entry, f, indent=2, ensure_ascii=False)

    # 写当前handoff（下个session读这个）
    md = f"""# Session Handoff — {timestamp}

## ✅ 做了什么
{what}

## 🔧 怎么做的
{how}

## 💡 为什么这样做（替代方案排除）
{why}

## ⏭️ 下一步精确输入
{next_step}

## 📁 涉及文件
{chr(10).join('- ' + f for f in entry['files_changed']) if entry['files_changed'] else '(无)'}

## ⚠️ 风险/注意
{risks or '(无)'}

---
_Generated by session_handoff.py | Session: {sid}_
"""
    with open(HANDOFF_CURRENT, "w") as f:
        f.write(md)

    print(f"✅ Handoff written: {HANDOFF_CURRENT}")
    print(f"   History: {history_file}")
    return entry


def read_current():
    """读当前handoff"""
    if not HANDOFF_CURRENT.exists():
        print("❌ No current handoff found.")
        return None
    with open(HANDOFF_CURRENT) as f:
        content = f.read()
    print(content)
    return content


def list_history(limit: int = 10):
    """列出历史handoffs"""
    if not HANDOFF_DIR.exists():
        print("No handoff history.")
        return
    files = sorted(HANDOFF_DIR.glob("*.json"), reverse=True)[:limit]
    for f in files:
        with open(f) as fh:
            entry = json.load(fh)
        print(f"  {entry['timestamp']} | {entry['session_id'][:20]} | {entry['what'][:60]}")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Session Handoff")
    sub = parser.add_subparsers(dest="cmd")

    p_write = sub.add_parser("write", help="Write handoff")
    p_write.add_argument("--what", required=True, help="做了什么")
    p_write.add_argument("--how", required=True, help="怎么做的（完整命令）")
    p_write.add_argument("--why", required=True, help="为什么这样做")
    p_write.add_argument("--next", required=True, dest="next_step", help="下一步精确输入")
    p_write.add_argument("--files", default="", help="涉及文件（逗号分隔）")
    p_write.add_argument("--risks", default="", help="风险/注意")
    p_write.add_argument("--session", default="")

    sub.add_parser("read", help="Read current handoff")
    p_list = sub.add_parser("list", help="List handoff history")
    p_list.add_argument("--limit", type=int, default=10)

    args = parser.parse_args()

    if args.cmd == "write":
        write_handoff(args.what, args.how, args.why, args.next_step,
                      args.files, args.session, args.risks)
    elif args.cmd == "read":
        read_current()
    elif args.cmd == "list":
        list_history(args.limit)
    else:
        parser.print_help()
